### ISSUE TITLE
Fix broadcast()

### ISSUE THREAD

**Issue by nalimilan** [JuliaStats/NullableArrays.jl#153]
We really need to fix this:

``` julia
julia> isnull.(NullableArray(1:3))
ERROR: MethodError: no method matching broadcast_shape(::NullableArrays.NullableArray{Int64,1})
Closest candidates are:
  broadcast_shape(::Tuple) at broadcast.jl:53
  broadcast_shape(::Tuple, ::Tuple, ::Tuple...) at broadcast.jl:54
 in broadcast(::Function, ::NullableArrays.NullableArray{Int64,1}) at ./<missing>:0

```

**Comment by davidagold** [comment]
We do. I'm pretty tired of trying to track changes to `broadcast` in Base. I vote that we just stop hosting our own `broadcast` implementation entirely, and rely on the `AbstractArray` interface. AFAICT, the only things we'd lose are
1. some performance since we're no longer operating directly on the `:values` and `:isnull` fields of the argument `NullableArray`s
2. the `lift` keyword argument

I'm fine with both of those for now.

**Comment by nalimilan** [comment]
I don't have the experience of working with that code myself, so I can't really tell what's best. But indeed if we can't fix it soon, better rely on the Base implementation.

Also, regarding 1, I would have thought the compiler would be able to optimize `getindex` away. But I haven't checked (and I think you did). Regarding 2, your `lift` function could be a good replacement (and a more general one).

**Comment by davidagold** [comment]
I haven't checked. I need to learn how to read lowered code. And yes, I intend the higher-order `lift` function to be a solution for this case, since writing `broadcast(f, X, lift=true)` is not any more convenient than writing `broadcast(lift(f), X)`.

**Comment by nalimilan** [comment]
Turns out these functions were simply renamed (not sure that was a good idea...). See https://github.com/JuliaStats/NullableArrays.jl/pull/164.

So we can wait until we're more confident about removing the special methods for `broadcast`.
